/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package fi.soveltia.liferay.aitasks.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ExternalReferenceCodeModel;
import com.liferay.portal.kernel.model.LocalizedModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.model.WorkflowedModel;

import java.util.Date;
import java.util.Locale;
import java.util.Map;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the AITask service. Represents a row in the &quot;AITask&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>fi.soveltia.liferay.aitasks.model.impl.AITaskModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>fi.soveltia.liferay.aitasks.model.impl.AITaskImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AITask
 * @generated
 */
@ProviderType
public interface AITaskModel
	extends BaseModel<AITask>, ExternalReferenceCodeModel, LocalizedModel,
			MVCCModel, ShardedModel, StagedAuditedModel, WorkflowedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a ai task model instance should use the {@link AITask} interface instead.
	 */

	/**
	 * Returns the primary key of this ai task.
	 *
	 * @return the primary key of this ai task
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this ai task.
	 *
	 * @param primaryKey the primary key of this ai task
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this ai task.
	 *
	 * @return the mvcc version of this ai task
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this ai task.
	 *
	 * @param mvccVersion the mvcc version of this ai task
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the uuid of this ai task.
	 *
	 * @return the uuid of this ai task
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this ai task.
	 *
	 * @param uuid the uuid of this ai task
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the external reference code of this ai task.
	 *
	 * @return the external reference code of this ai task
	 */
	@AutoEscape
	@Override
	public String getExternalReferenceCode();

	/**
	 * Sets the external reference code of this ai task.
	 *
	 * @param externalReferenceCode the external reference code of this ai task
	 */
	@Override
	public void setExternalReferenceCode(String externalReferenceCode);

	/**
	 * Returns the ai task ID of this ai task.
	 *
	 * @return the ai task ID of this ai task
	 */
	public long getAITaskId();

	/**
	 * Sets the ai task ID of this ai task.
	 *
	 * @param aiTaskId the ai task ID of this ai task
	 */
	public void setAITaskId(long aiTaskId);

	/**
	 * Returns the company ID of this ai task.
	 *
	 * @return the company ID of this ai task
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this ai task.
	 *
	 * @param companyId the company ID of this ai task
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this ai task.
	 *
	 * @return the user ID of this ai task
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this ai task.
	 *
	 * @param userId the user ID of this ai task
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this ai task.
	 *
	 * @return the user uuid of this ai task
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this ai task.
	 *
	 * @param userUuid the user uuid of this ai task
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this ai task.
	 *
	 * @return the user name of this ai task
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this ai task.
	 *
	 * @param userName the user name of this ai task
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this ai task.
	 *
	 * @return the create date of this ai task
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this ai task.
	 *
	 * @param createDate the create date of this ai task
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this ai task.
	 *
	 * @return the modified date of this ai task
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this ai task.
	 *
	 * @param modifiedDate the modified date of this ai task
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the configuration json of this ai task.
	 *
	 * @return the configuration json of this ai task
	 */
	@AutoEscape
	public String getConfigurationJSON();

	/**
	 * Sets the configuration json of this ai task.
	 *
	 * @param configurationJSON the configuration json of this ai task
	 */
	public void setConfigurationJSON(String configurationJSON);

	/**
	 * Returns the enabled of this ai task.
	 *
	 * @return the enabled of this ai task
	 */
	public boolean getEnabled();

	/**
	 * Returns <code>true</code> if this ai task is enabled.
	 *
	 * @return <code>true</code> if this ai task is enabled; <code>false</code> otherwise
	 */
	public boolean isEnabled();

	/**
	 * Sets whether this ai task is enabled.
	 *
	 * @param enabled the enabled of this ai task
	 */
	public void setEnabled(boolean enabled);

	/**
	 * Returns the description of this ai task.
	 *
	 * @return the description of this ai task
	 */
	public String getDescription();

	/**
	 * Returns the localized description of this ai task in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized description of this ai task
	 */
	@AutoEscape
	public String getDescription(Locale locale);

	/**
	 * Returns the localized description of this ai task in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized description of this ai task. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getDescription(Locale locale, boolean useDefault);

	/**
	 * Returns the localized description of this ai task in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized description of this ai task
	 */
	@AutoEscape
	public String getDescription(String languageId);

	/**
	 * Returns the localized description of this ai task in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized description of this ai task
	 */
	@AutoEscape
	public String getDescription(String languageId, boolean useDefault);

	@AutoEscape
	public String getDescriptionCurrentLanguageId();

	@AutoEscape
	public String getDescriptionCurrentValue();

	/**
	 * Returns a map of the locales and localized descriptions of this ai task.
	 *
	 * @return the locales and localized descriptions of this ai task
	 */
	public Map<Locale, String> getDescriptionMap();

	/**
	 * Sets the description of this ai task.
	 *
	 * @param description the description of this ai task
	 */
	public void setDescription(String description);

	/**
	 * Sets the localized description of this ai task in the language.
	 *
	 * @param description the localized description of this ai task
	 * @param locale the locale of the language
	 */
	public void setDescription(String description, Locale locale);

	/**
	 * Sets the localized description of this ai task in the language, and sets the default locale.
	 *
	 * @param description the localized description of this ai task
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setDescription(
		String description, Locale locale, Locale defaultLocale);

	public void setDescriptionCurrentLanguageId(String languageId);

	/**
	 * Sets the localized descriptions of this ai task from the map of locales and localized descriptions.
	 *
	 * @param descriptionMap the locales and localized descriptions of this ai task
	 */
	public void setDescriptionMap(Map<Locale, String> descriptionMap);

	/**
	 * Sets the localized descriptions of this ai task from the map of locales and localized descriptions, and sets the default locale.
	 *
	 * @param descriptionMap the locales and localized descriptions of this ai task
	 * @param defaultLocale the default locale
	 */
	public void setDescriptionMap(
		Map<Locale, String> descriptionMap, Locale defaultLocale);

	/**
	 * Returns the read only of this ai task.
	 *
	 * @return the read only of this ai task
	 */
	public boolean getReadOnly();

	/**
	 * Returns <code>true</code> if this ai task is read only.
	 *
	 * @return <code>true</code> if this ai task is read only; <code>false</code> otherwise
	 */
	public boolean isReadOnly();

	/**
	 * Sets whether this ai task is read only.
	 *
	 * @param readOnly the read only of this ai task
	 */
	public void setReadOnly(boolean readOnly);

	/**
	 * Returns the schema version of this ai task.
	 *
	 * @return the schema version of this ai task
	 */
	@AutoEscape
	public String getSchemaVersion();

	/**
	 * Sets the schema version of this ai task.
	 *
	 * @param schemaVersion the schema version of this ai task
	 */
	public void setSchemaVersion(String schemaVersion);

	/**
	 * Returns the title of this ai task.
	 *
	 * @return the title of this ai task
	 */
	public String getTitle();

	/**
	 * Returns the localized title of this ai task in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized title of this ai task
	 */
	@AutoEscape
	public String getTitle(Locale locale);

	/**
	 * Returns the localized title of this ai task in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized title of this ai task. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getTitle(Locale locale, boolean useDefault);

	/**
	 * Returns the localized title of this ai task in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized title of this ai task
	 */
	@AutoEscape
	public String getTitle(String languageId);

	/**
	 * Returns the localized title of this ai task in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized title of this ai task
	 */
	@AutoEscape
	public String getTitle(String languageId, boolean useDefault);

	@AutoEscape
	public String getTitleCurrentLanguageId();

	@AutoEscape
	public String getTitleCurrentValue();

	/**
	 * Returns a map of the locales and localized titles of this ai task.
	 *
	 * @return the locales and localized titles of this ai task
	 */
	public Map<Locale, String> getTitleMap();

	/**
	 * Sets the title of this ai task.
	 *
	 * @param title the title of this ai task
	 */
	public void setTitle(String title);

	/**
	 * Sets the localized title of this ai task in the language.
	 *
	 * @param title the localized title of this ai task
	 * @param locale the locale of the language
	 */
	public void setTitle(String title, Locale locale);

	/**
	 * Sets the localized title of this ai task in the language, and sets the default locale.
	 *
	 * @param title the localized title of this ai task
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setTitle(String title, Locale locale, Locale defaultLocale);

	public void setTitleCurrentLanguageId(String languageId);

	/**
	 * Sets the localized titles of this ai task from the map of locales and localized titles.
	 *
	 * @param titleMap the locales and localized titles of this ai task
	 */
	public void setTitleMap(Map<Locale, String> titleMap);

	/**
	 * Sets the localized titles of this ai task from the map of locales and localized titles, and sets the default locale.
	 *
	 * @param titleMap the locales and localized titles of this ai task
	 * @param defaultLocale the default locale
	 */
	public void setTitleMap(Map<Locale, String> titleMap, Locale defaultLocale);

	/**
	 * Returns the version of this ai task.
	 *
	 * @return the version of this ai task
	 */
	@AutoEscape
	public String getVersion();

	/**
	 * Sets the version of this ai task.
	 *
	 * @param version the version of this ai task
	 */
	public void setVersion(String version);

	/**
	 * Returns the status of this ai task.
	 *
	 * @return the status of this ai task
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this ai task.
	 *
	 * @param status the status of this ai task
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this ai task.
	 *
	 * @return the status by user ID of this ai task
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this ai task.
	 *
	 * @param statusByUserId the status by user ID of this ai task
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this ai task.
	 *
	 * @return the status by user uuid of this ai task
	 */
	@Override
	public String getStatusByUserUuid();

	/**
	 * Sets the status by user uuid of this ai task.
	 *
	 * @param statusByUserUuid the status by user uuid of this ai task
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this ai task.
	 *
	 * @return the status by user name of this ai task
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this ai task.
	 *
	 * @param statusByUserName the status by user name of this ai task
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this ai task.
	 *
	 * @return the status date of this ai task
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this ai task.
	 *
	 * @param statusDate the status date of this ai task
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns <code>true</code> if this ai task is approved.
	 *
	 * @return <code>true</code> if this ai task is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this ai task is denied.
	 *
	 * @return <code>true</code> if this ai task is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this ai task is a draft.
	 *
	 * @return <code>true</code> if this ai task is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this ai task is expired.
	 *
	 * @return <code>true</code> if this ai task is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this ai task is inactive.
	 *
	 * @return <code>true</code> if this ai task is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this ai task is incomplete.
	 *
	 * @return <code>true</code> if this ai task is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this ai task is pending.
	 *
	 * @return <code>true</code> if this ai task is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this ai task is scheduled.
	 *
	 * @return <code>true</code> if this ai task is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

	@Override
	public String[] getAvailableLanguageIds();

	@Override
	public String getDefaultLanguageId();

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException;

	@Override
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException;

	@Override
	public AITask cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}